// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeZOEBZPP-W6dCOvE0hiSApaiO_sFsN_8',
    appId: '1:592891672732:web:1cc961fd4b6c70ac835559',
    messagingSenderId: '592891672732',
    projectId: 'cmsc23-todo-app-jvesguerra',
    authDomain: 'cmsc23-todo-app-jvesguerra.firebaseapp.com',
    storageBucket: 'cmsc23-todo-app-jvesguerra.appspot.com',
    measurementId: 'G-W76SWV66QJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk9Tu80GQT83KdidmiwmBufcgzX2BOWfw',
    appId: '1:592891672732:android:165327260f365cfc835559',
    messagingSenderId: '592891672732',
    projectId: 'cmsc23-todo-app-jvesguerra',
    storageBucket: 'cmsc23-todo-app-jvesguerra.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ99e3NRySYVDAJHA_8P3ukRQKqumBxqs',
    appId: '1:592891672732:ios:9653b12cf6e1ac41835559',
    messagingSenderId: '592891672732',
    projectId: 'cmsc23-todo-app-jvesguerra',
    storageBucket: 'cmsc23-todo-app-jvesguerra.appspot.com',
    iosClientId: '592891672732-retjh4aqvkqpvue6ofgqmrihbfh8r0a7.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ99e3NRySYVDAJHA_8P3ukRQKqumBxqs',
    appId: '1:592891672732:ios:9653b12cf6e1ac41835559',
    messagingSenderId: '592891672732',
    projectId: 'cmsc23-todo-app-jvesguerra',
    storageBucket: 'cmsc23-todo-app-jvesguerra.appspot.com',
    iosClientId: '592891672732-retjh4aqvkqpvue6ofgqmrihbfh8r0a7.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}
